databases:
  - name: Budgetapp
    databaseName: budgetapp_cve7
    user: budgetapp_cve7_user

services:
  - type: web
    name: Budgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp_cve7
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false